from proteinTools import *

APAP = Modification (
        'APAP',
        netFormulaChange = 'C8H7NO2',
        reactiveResidues = ['C']
)

MGST = Protein(
    '''MADLKQLMDNEVLMAFTSYATIILAKMMFLSSATAFQRLTNKVFANPEDCAGFGKGENAK
    KFLRTDEKVERVRRAHLNDLENIVPFLGIGLLYSLSGPDLSTALIHFRIFVGARIYHTIA
    YLTPLPQPNRGLAFFVGYGVTLSMAYRLLRSRLYL''')

HSA = Protein(
    '''DAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFEDHVKLVNEVTEFAKTCVADESAENCDKSLHTLFGDKLCTVATL
    RETYGEMADCCAKQEPERNECFLQHKDDNPNLPRLVRPEVDVMCTAFHDNEETFLKKYLYEIARRHPYFYAPELLFFAKR
    YKAAFTECCQAADKAACLLPKLDELRDEGKASSAKQRLKCASLQKFGERAFKAWAVARLSQRFPKAEFAEVSKLVTDLTK
    VHTECCHGDLLECADDRADLAKYICENQDSISSKLKECCEKPLLEKSHCIAEVENDEMPADLPSLAADFVESKDVCKNYA
    EAKDVFLGMFLYEYARRHPDYSVVLLLRLAKTYETTLEKCCAAADPHECYAKVFDEFKPLVEEPQNLIKQNCELFEQLGE
    YKFQNALLVRYTKKVPQVSTPTLVEVSRNLGKVGSKCCKHPEAKRMPCAEDYLSVVLNQLCVLHEKTPVSDRVTKCCTES
    LVNRRPCFSALEVDETYVPKEFNAETFTFHADICTLSEKERQIKKQTALVELVKHKPKATKEQLKAVMDDFAAFVEKCCK
    ADDKETCFAEEGKKLVAASQAALGL'''
)

MGST.applyModification(APAP)
MGST.digest()

for p in MGST.peptides:
    print p.sequence, p.pseudoMolecularIons
